#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七
#八 九 十
#bspc monitor -d       
#bspc monitor -d 1 2 3 4 5 6 7
#bspc monitor -d  1    ♪          
# formal numerals now
# bspc monitor -d 壱 弐 参 肆 伍 陸 漆

getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
xrdb ~/.Xresources

bspc config border_radius        1
bspc config border_width         3
bspc config window_gap           9

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color "#$color8"
bspc config active_border_color "#$color9"
bspc config focused_border_color "#$color9"
bspc config presel_feedback_color "#$color1"

bspc rulc -a discord desktop=^4 follow=off
bspc rulc -a Gimp desktop=^5 state=floating follow=on
bspc rulc -a Brave-browser desktop=^2 follow=off
bspc rule -a Pulseeffects desktop=^7 follow=off
bspc rulc -a mplayer2 state=floating
bspc rulc -a Kupfer.py focus=on
bspc rulc -a Screenkey manage=off

# Autostart
colors.sh &
volumeicon &
pulseeffects &
xrandr --output VGA-0 --mode 1368x768
$HOME/.config/polybar/launch.sh
picom -f &
wal -R &

dunst &
sleep 0.15
notify-send "Welcome Zola! ;)"
